version: "3.4"

services:
  pg_tileserv:
    image: pramsey/pg_tileserv:latest
    ports:
      - "7800:7800"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
    volumes:
      - ./pg_tileserv.toml:/etc/pg_tileserv.toml
    restart: always

  pg_featureserv:
    image: pramsey/pg_featureserv:latest
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
    restart: always

  server-web:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./apps/index.html:/usr/share/nginx/html/index.html
      - ./apps/style.css:/usr/share/nginx/html/style.css
      - ./apps/vignette_photo:/usr/share/nginx/html/vignette_photo
      - ./apps/script.js:/usr/share/nginx/html/script.js
      - ./apps/server.js:/usr/share/nginx/html/server.js
    restart: always